/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    OdosButton: (typeof import('../packages/Button/src/index.vue'))['default']
    OdosIcon: (typeof import('../packages/Icon/src/index.vue'))['default']
    OdosInput: (typeof import('../packages/Input/src/index.vue'))['default']
    OdosInputNumber: (typeof import('../packages/InputNumber/src/index.vue'))['default']
    OdosPopover: (typeof import('../packages/Popover/src/index.vue'))['default']
    OdosRadio: (typeof import('../packages/Radio/src/index.vue'))['default']
    OdosRadioItem: (typeof import('../packages/Radio/src/item.vue'))['default']
    OdosSelect: (typeof import('../packages/Select/src/index.vue'))['default']
    OdosCheckBox: (typeof import('../packages/CheckBox/src/index.vue'))['default']
    OdosCheckBoxItem: (typeof import('../packages/CheckBox/src/item.vue'))['default']
    OdosDatePicker: (typeof import('../packages/datePicker/src/index.vue'))['default']
    OdosTable: (typeof import('../packages/Table/src/index.vue'))['default']
    OdosTag: (typeof import('../packages/Tag-Comp/src/index.vue'))['default']
    OdosTextarea: (typeof import('../packages/Textarea/src/index.vue'))['default']
    OdosPagination: (typeof import('../packages/Pagination/src/index.vue'))['default']
  }
}
