/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

export interface GlobalComponents {
  OdosAudio: (typeof import('../packages/Audio/src/index.vue'))['default']
  OdosButton: (typeof import('../packages/Button/src/index.vue'))['default']
  OdosCheckBox: (typeof import('../packages/CheckBox/src/index.vue'))['default']
  OdosCheckBoxItem: (typeof import('../packages/CheckBox/src/item.vue'))['default']
  OdosDatePicker: (typeof import('../packages/datePicker/src/index.vue'))['default']
  OdosEmpty: (typeof import('../packages/Empty/src/index.vue'))['default']
  OdosForm: (typeof import('../packages/Form/src/index.vue'))['default']
  OdosFormItem: (typeof import('../packages/Form/src/item.vue'))['default']
  OdosIcon: (typeof import('../packages/Icon/src/index.vue'))['default']
  OdosInput: (typeof import('../packages/Input/src/index.vue'))['default']
  OdosInputNumber: (typeof import('../packages/InputNumber/src/index.vue'))['default']
  OdosModal: (typeof import('../packages/Modal/src/index.vue'))['default']
  OdosPopover: (typeof import('../packages/Popover/src/index.vue'))['default']
  OdosRadio: (typeof import('../packages/Radio/src/index.vue'))['default']
  OdosRadioItem: (typeof import('../packages/Radio/src/item.vue'))['default']
  OdosSelect: (typeof import('../packages/Select/src/index.vue'))['default']
  OdosToothChart: (typeof import('../packages/ToothChart/src/index.vue'))['default']
  OdosToothSelect: (typeof import('../packages/ToothSelect/src/index.vue'))['default']
  OdosTable: (typeof import('../packages/Table/src/index.vue'))['default']
  OdosTabs: (typeof import('../packages/Tabs/src/index.vue'))['default']
  OdosTab: (typeof import('../packages/Tabs/src/item.vue'))['default']
  OdosTag: (typeof import('../packages/Tag/src/index.vue'))['default']
  OdosTextarea: (typeof import('../packages/Textarea/src/index.vue'))['default']
  OdosPagination: (typeof import('../packages/Pagination/src/index.vue'))['default']
  OdosTooltip: (typeof import('../packages/Tooltip/src/index.vue'))['default']
}
